[build-system]
requires = ["setuptools>=61.0", "pandas==1.5.3"]
build-backend = "setuptools.build_meta"

[project]
name = "money"
version = "0.0.1"
authors = [
  { name="lombo-cmyk"},
]
description = "moneymoneymoney"
readme = "README.md"
requires-python = ">=3.8"
